### ISSUE TITLE
luarock install mecab fails with mecab-1.0-4

### ISSUE THREAD

**Issue by kenhys** [polm/lua-mecab#4]
It seems that required fix for rockspec is not included yet.

```

% LANG=C luarocks install mecab
Installing https://luarocks.org/mecab-1.0-4.src.rock
g++ -fPIC -c lua-mecab.cpp -o lua-mecab.o
lua-mecab.cpp:2:17: fatal error: lua.h: No such file or directory
 #include <lua.h>
                 ^
compilation terminated.
Makefile:13: recipe for target 'lua-mecab.o' failed
make: *** [lua-mecab.o] Error 1

Error: Build error: Failed building.
```

https://github.com/polm/lua-mecab/blob/master/mecab-dev-1.rockspec and https://luarocks.org/manifests/23/mecab-1.0-4.rockspec are bit different. How managed this rockspec is?

**Comment by polm** [comment]
Thanks for the bug report. I copied the rockspec based on the old one and forgot to update the git tag and environment variables; I pushed an update that should hopefully be correct. Please let me know if it works.

**Comment by kenhys** [comment]
Thanks!

I've confirmed that new version works as expected.

```
% luarocks install mecab
Installing https://luarocks.org/mecab-1.0-5.src.rock
g++ -I/home/kenhys/.luaenv/versions/5.2.4/include -fPIC -c lua-mecab.cpp -o lua-mecab.o
g++ -shared lua-mecab.o `mecab-config --libs` -o lua-mecab.so
cp lua-mecab.so /home/kenhys/.luaenv/versions/5.2.4/lib/luarocks/rocks/mecab/1.0-5/lib/mecab.so
mecab 1.0-5 is now installed in /home/kenhys/.luaenv/versions/5.2.4 (license: WTFPL)
```

**Comment by kenhys** [comment]
I'll close this issue.
Thanks!

**Comment by polm** [comment]
Thanks for the update, glad to hear it works!
